version: '3.5'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - PGDATA=/data/postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: ./
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 15; done; uvicorn main:app --host 0.0.0.0'
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/reports
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SUPERUSER_NAME=${SUPERUSER_NAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    depends_on:
      - db
    ports:
      - 8555:8000
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres:
