version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "32761:5432"
    networks:
      - postgres
    restart: unless-stopped

  web:
    build: ./
    container_name: web
    depends_on:
      - postgres
    network_mode: host
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
