version: '3'

services:

  postgres:
    image:  postgres:11
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: reports
      POSTGRES_DB: reports

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_OUT_PORT}:80
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge