version: '3'

services:

  postgres:
    image:  postgres:11
    ports:
      - ${PG_OUT_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reports

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PG_ADMIN_OUT_PORT}:80
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge